language: python
python:
  - "3.6"

sudo: false

cache: pip

install:
  - pip install -r requirements.txt -e .

script:
  - py.test --cov=. tests/
  - flake8 pytest_docker_tools tests

after_success:
  - codecov
