language: python
python:
  - "3.6"

sudo: required

services:
  - docker

cache: pip

install:
  - pip install -r requirements.txt -e .

script:
  - coverage run --source pytest_docker_tools -m py.test
  - flake8 pytest_docker_tools tests

after_success:
  - codecov
