name: CI

on:
  push:
    branches:
    - main
  pull_request: ~

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout and install dependencies
      uses: Jc2k/actions-poetry@main
      with:
        python-version: 3.7

    - name: Run pyupgrade
      shell: bash
      run: poetry run find pytest_docker_tools tests -name '*.py' -exec python -m pyupgrade --py37-plus {} + && git diff --exit-code

    - name: Run isort
      shell: bash
      run: poetry run python -m isort -c --diff pytest_docker_tools tests

    - name: Run black
      shell: bash
      run: poetry run python -m black --check --diff pytest_docker_tools tests

    - name: Run flake8
      shell: bash
      run: poetry run python -m flake8 pytest_docker_tools tests

    - name: Run poetry build
      shell: bash
      run: poetry build

    - name: Run poetry check
      shell: bash
      run: poetry check

  tests:
    name: pytest/${{ matrix.os }}/${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}-latest

    strategy:
      matrix:
        # os: [Ubuntu, MacOS, Windows]
        # Development primarily happens on macOS, it does work with Docker for Mac
        # Windows is not tested at all
        # Neither are currently an option on GitHub CI
        os: [Ubuntu]
        python-version: [3.7, 3.8]

    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}

    steps:
    - name: Checkout and install dependencies
      uses: Jc2k/actions-poetry@main
      with:
        python-version: ${{ matrix.python-version }}

    - name: Run pytest
      shell: bash
      run: poetry run coverage run -m pytest

    - name: Upload coverage to Codecov
      shell: bash
      run: poetry run codecov --flags unittests -e OS -e PYTHON --tries 20
