
name: Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  Release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout and install dependencies
        uses: Jc2k/actions-poetry@main
        with:
          python-version: 3.7

      - name: Get tag
        id: tag
        run: |
          echo ::set-output name=tag::${GITHUB_REF#refs/tags/}

      - name: Build project for distribution
        run: poetry run poetry build

      - name: Publish to PyPI
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
        run: poetry run poetry publish

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          release_name: ${{ steps.tag.outputs.tag }}
          draft: false
          prerelease: false

      - name: Upload Linux release file asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/pytest_docker_tools-${{ steps.tag.outputs.tag }}.tar.gz
          asset_name: pytest_docker_tools-${{ steps.tag.outputs.tag }}.tar.gz
          asset_content_type: application/gzip

      - name: Upload Linux checksum file asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/pytest_docker_tools-${{ steps.tag.outputs.tag }}-py3-none-any.whl
          asset_name: pytest_docker_tools-${{ steps.tag.outputs.tag }}-py3-none-any.whl
          asset_content_type: application/x-wheel+zip